# Generated by Django 5.1.2 on 2025-02-04 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["-date_submitted"]},
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="email",
        ),
        migrations.AddField(
            model_name="ticket",
            name="ai_response",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ticket",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("arts_humanities", "Arts & Humanities"),
                    ("business", "Business"),
                    ("dentistry", "Dentistry, Oral & Craniofacial Sciences"),
                    ("law", "Law"),
                    ("life_sciences_medicine", "Life Sciences & Medicine"),
                    (
                        "natural_mathematical_engineering",
                        "Natural, Mathematical & Engineering Sciences",
                    ),
                    ("nursing", "Nursing, Midwifery & Palliative Care"),
                    ("psychiatry", "Psychiatry, Psychology & Neuroscience"),
                    ("social_science", "Social Science & Public Policy"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="priority",
            field=models.CharField(
                blank=True,
                choices=[("low", "Low"), ("normal", "Normal"), ("urgent", "Urgent")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submitted_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="ticket.message",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="ticket.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
