# Generated by Django 5.1.2 on 2025-03-26 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_ticket_options_remove_ticket_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 25, 14, 5, 36, 621367, tzinfo=datetime.timezone.utc)),
        ),
    ]
