# Generated by Django 5.1.2 on 2025-03-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_department_alter_announcement_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='department',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
