# Generated by Django 5.1.2 on 2025-04-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_department_email_department_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
