# Generated by Django 5.1.2 on 2025-03-26 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_alter_ticket_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 25, 14, 9, 27, 368406, tzinfo=datetime.timezone.utc)),
        ),
    ]
