# Generated by Django 5.1.2 on 2025-02-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
