# Generated by Django 5.1.2 on 2025-02-24 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_alter_staff_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 26, 22, 1, 35, 983335, tzinfo=datetime.timezone.utc)),
        ),
    ]
