# Generated by Django 4.2.17 on 2025-02-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_alter_staff_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='message_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
