# Generated by Django 5.1.2 on 2025-02-24 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_ticket_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 26, 22, 5, 52, 988576, tzinfo=datetime.timezone.utc)),
        ),
    ]
