# Generated by Django 5.1.2 on 2025-02-25 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_alter_ticket_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 27, 13, 1, 45, 407193, tzinfo=datetime.timezone.utc)),
        ),
    ]
