# Generated by Django 5.1.2 on 2025-03-04 03:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0012_alter_ticket_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 3, 3, 33, 25, 440528, tzinfo=datetime.timezone.utc)),
        ),
    ]
