# Generated by Django 5.1.2 on 2025-03-09 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_ticket_message_id'),
        ('ticket', '0013_alter_ticket_expiration_date'),
    ]

    operations = [
    ]
