# Generated by Django 4.2.17 on 2025-03-12 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0016_ticket_rating_ticket_rating_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 11, 16, 38, 45, 929674, tzinfo=datetime.timezone.utc)),
        ),
    ]
