# Generated by Django 5.1.2 on 2025-03-12 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0016_ticket_rating_ticket_rating_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 11, 16, 13, 25, 161476, tzinfo=datetime.timezone.utc)),
        ),
    ]
