# Generated by Django 5.1.2 on 2025-03-13 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0017_alter_ticket_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 12, 18, 12, 49, 325829, tzinfo=datetime.timezone.utc)),
        ),
    ]
