# Generated by Django 4.2.17 on 2025-03-23 00:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0018_alter_ticket_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 22, 0, 8, 20, 594242, tzinfo=datetime.timezone.utc)),
        ),
    ]
