# Generated by Django 5.1.2 on 2025-03-13 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0018_alter_ticket_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 12, 19, 20, 15, 741011, tzinfo=datetime.timezone.utc)),
        ),
    ]
