# Generated by Django 5.1.2 on 2025-03-16 18:06

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0019_alter_ticket_expiration_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="expiration_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 4, 15, 18, 6, 36, 509305, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Select Department"),
                            ("arts_humanities", "Arts & Humanities"),
                            ("business", "Business"),
                            ("dentistry", "Dentistry"),
                            ("law", "Law"),
                            ("life_sciences_medicine", "Life Sciences & Medicine"),
                            (
                                "natural_mathematical_engineering",
                                "Natural, Mathematical & Engineering Sciences",
                            ),
                            ("nursing", "Nursing"),
                            ("psychiatry", "Psychiatry"),
                            ("social_science", "Social Science"),
                        ],
                        help_text="If left blank, the announcement will be sent to all departments",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
