# Generated by Django 5.1.2 on 2025-03-16 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0020_alter_ticket_expiration_date_announcement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="announcement",
            name="title",
        ),
        migrations.AlterField(
            model_name="announcement",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Select Department"),
                    ("arts_humanities", "Arts & Humanities"),
                    ("business", "Business"),
                    ("dentistry", "Dentistry"),
                    ("law", "Law"),
                    ("life_sciences_medicine", "Life Sciences & Medicine"),
                    (
                        "natural_mathematical_engineering",
                        "Natural, Mathematical & Engineering Sciences",
                    ),
                    ("nursing", "Nursing"),
                    ("psychiatry", "Psychiatry"),
                    ("social_science", "Social Science"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="expiration_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 4, 15, 18, 8, 28, 693293, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
