# Generated by Django 5.1.2 on 2025-03-18 22:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0021_remove_announcement_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 17, 22, 47, 21, 734964, tzinfo=datetime.timezone.utc)),
        ),
    ]
