# Generated by Django 5.1.2 on 2025-03-20 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0022_alter_ticket_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='remember_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='remember_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 19, 17, 13, 51, 384277, tzinfo=datetime.timezone.utc)),
        ),
    ]
