# Generated by Django 5.1.2 on 2025-03-20 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0023_customuser_remember_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 19, 19, 29, 30, 480535, tzinfo=datetime.timezone.utc)),
        ),
    ]
