# Generated by Django 5.1.2 on 2025-03-20 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0024_alter_ticket_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 19, 23, 4, 59, 458958, tzinfo=datetime.timezone.utc)),
        ),
    ]
