# Generated by Django 4.2.17 on 2025-03-23 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0019_customuser_is_email_verified_and_more'),
        ('ticket', '0025_alter_ticket_expiration_date'),
    ]

    operations = [
    ]
