# Generated by Django 5.1.2 on 2025-03-20 23:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0028_alter_ticket_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 19, 23, 55, 1, 138708, tzinfo=datetime.timezone.utc)),
        ),
    ]
