# Generated by Django 5.1.2 on 2025-03-21 00:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0029_alter_ticket_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 20, 0, 19, 1, 126185, tzinfo=datetime.timezone.utc)),
        ),
    ]
