# Generated by Django 5.1.2 on 2025-03-22 02:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0033_alter_ticket_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='admin_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 21, 2, 38, 18, 424341, tzinfo=datetime.timezone.utc)),
        ),
    ]
