# Generated by Django 5.1.2 on 2025-03-22 22:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0036_alter_ticket_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 21, 22, 59, 15, 933676, tzinfo=datetime.timezone.utc)),
        ),
    ]
