# Generated by Django 5.1.2 on 2025-03-22 23:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0037_alter_ticket_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 21, 23, 49, 36, 113770, tzinfo=datetime.timezone.utc)),
        ),
    ]
