# Generated by Django 5.1.2 on 2025-03-23 00:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0038_alter_ticket_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 22, 0, 16, 34, 242876, tzinfo=datetime.timezone.utc)),
        ),
    ]
