# Generated by Django 5.1.2 on 2025-03-23 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0039_alter_ticket_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 22, 22, 29, 8, 411045, tzinfo=datetime.timezone.utc)),
        ),
    ]
