# Generated by Django 5.1.2 on 2025-03-24 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0041_ticket_email_alter_ticket_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='email',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 23, 2, 56, 29, 740821, tzinfo=datetime.timezone.utc)),
        ),
    ]
