# Generated by Django 5.1.2 on 2025-03-24 03:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0042_remove_ticket_email_alter_ticket_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 23, 3, 8, 22, 956412, tzinfo=datetime.timezone.utc)),
        ),
    ]
