# Generated by Django 5.1.2 on 2025-03-24 03:49

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0044_alter_ticket_expiration_date_adminmessage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminmessage',
            options={},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 23, 3, 49, 33, 740048, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='StaffMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_messages', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_messages', to='ticket.ticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
