# Generated by Django 5.1.2 on 2025-03-24 04:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0045_alter_adminmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 23, 4, 24, 0, 599313, tzinfo=datetime.timezone.utc)),
        ),
    ]
