# Generated by Django 5.1.2 on 2025-03-24 04:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0049_alter_ticket_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 23, 4, 53, 44, 555382, tzinfo=datetime.timezone.utc)),
        ),
    ]
