# Generated by Django 5.1.2 on 2025-03-24 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0051_alter_ticket_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 23, 6, 51, 20, 915025, tzinfo=datetime.timezone.utc)),
        ),
    ]
